class AppAssertIcons {
  AppAssertIcons._privateConstructor();
  static final AppAssertIcons _instance = AppAssertIcons._privateConstructor();
  static AppAssertIcons get instance => _instance;

  final String home = "assets/icons/home.png";
  final String profile = "assets/icons/profile.png";
  final String reserve = "assets/icons/reserve.png";
  final String allOrder = "assets/icons/all_order.png";
  final String ballNotification = "assets/icons/ball_notification.png";
  final String filterButtonCircular = "assets/icons/filter_button_circular.png";
  final String logout = "assets/icons/logout.png";
  final String chat = "assets/icons/chat.png";
  final String reservation = "assets/icons/reservation.png";
  final String settings = "assets/icons/settings.png";
  final String editImage = "assets/icons/edit_image.png";
  final String mail = "assets/icons/mail.png";
  final String location = "assets/icons/location.png";
  final String send = "assets/icons/send.png";
  final String image = "assets/icons/image.png";
  final String seen = "assets/icons/seen.png";
  final String aboutUs = "assets/icons/about_us.png";
  final String delete = "assets/icons/delete.png";
  final String lock = "assets/icons/lock.png";
  final String privacyPolicy = "assets/icons/privacy_policy.png";
  final String termsAndCondition = "assets/icons/terms_and_condition.png";
  final String carColor = "assets/icons/car_color.png";
  final String carGear = "assets/icons/car_gear.png";
  final String carSeat = "assets/icons/car_seat.png";
  final String carType = "assets/icons/car_type.png";
  final String driveDuration = "assets/icons/drive_duration.png";
  final String fuelType = "assets/icons/fuel_type.png";
  final String addCircle = "assets/icons/add-circle.png";
  final String locationOutline = "assets/icons/location_outline.png";
  final String star = "assets/icons/Star.png";
  final String vehicle = "assets/icons/vehicle.png";
  final String activeOrder = "assets/icons/active_order.png";
  final String completedOrder = "assets/icons/completed_order.png";
  final String receivedOrder = "assets/icons/received_order.png";
  final String totalOrder = "assets/icons/total_order.png";
  final String car = "assets/icons/car.png";
  final String calender = "assets/icons/calender.png";
  final String clock = "assets/icons/clock.png";
  final String location2 = "assets/icons/location2.png";
}
